[package]
name = "client"
version = "0.1.0"
edition = "2021"

[dependencies]
common = { version = "0.1.0", path = "../common" }
lazy_static = "1.5.0"
serde_json = "1.0.140"
uuid = "1.15.1"
anyhow = "1.0.97"
base64 = "0.22.1"
thiserror = "2.0.12"
