[package]
name = "homework-09"
version = "1.0.0"
edition = "2021"

[dependencies]
chrono = "0.4.39"
clap = "4.5.30"
lazy_static = "1.5.0"
serde = { version = "1.0.217", features = ["derive", "serde_derive"] }
serde_json = "1.0.138"
regex = "1.11.1"
image = "0.25.5"
