[package]
name = "common"
version = "0.1.0"
edition = "2021"

[dependencies]
clap = "4.5.31"
serde = { version = "1.0.219", features = ["derive"] }
uuid = { version = "1.15.1", features = ["v4"] }
serde_json = "1.0.140"
hostname = "0.4.0"
