[package]
name = "server"
version = "0.1.0"
edition = "2021"

[dependencies]
common = { version = "0.1.0", path = "../common" }
chrono = "0.4.39"
lazy_static = "1.5.0"
regex = "1.11.1"
image = "0.25.5"
